Repository kanha-43/Add-a-javascipt-bot, pull requests merged in 2022-10, with the labels that each got.

#2 chatbotadded
  index.html
  style.css
Labels: hacktoberfest-accepted

#5 js page adding
  index.js
  response.js
  svg/robot.svg
Labels: hacktoberfest-accepted

#8 Styling added
  .vscode/settings.json
  index.html
  style.css
Labels: hacktoberfest-accepted, approved

#12 Revert "Added some bot responses and snowpack dev"
  .gitignore
  package-lock.json
  package.json
Labels: hacktoberfest-accepted, approved

#9 Create LICENSE.md
  LICENSE.md
Labels: approved, spam, under a review of 2 days

#16 Added a backup load balancer server
  BackupLoadBalancerServer.js
Labels: bug, hacktoberfest, hacktoberfest-accepted, approved

#18 Added the analytics file
  Analytics.js
Labels: hacktoberfest, hacktoberfest-accepted, approved
